#!/bin/bash
unset bank
echo ${bank:-Citi}
bank=HSBC
echo ${bank:-Citi}
unset bank
echo ${bank=Chase}
echo $bank
unset bank
echo ${bank:=BBOA}
echo ${bank}
bank=WellsFargo
echo ${bank:=Citi}
echo ${bank}
