#!/bin/bash
cal
echo "current wod directory is `pwd`"
echo 'current wod directory is `pwd`'
echo "homw directory is $HOME" 
echo 'homw directory is $HOME' 
echo "file*.c" 
ls
echo "----------"
#ls *.python 
today=`date` 
echo  $today 



