#!/bin/bash
echo "Path is $PATH"  ## $PATH will be expanded
#double quotes when you want only variables and command substitution.
#Variable - Yes
# Wildcards - No
# Command substitution -yes
echo 'I want to print $PATH' ## PATH will not be expanded

echo "Path is \$PATH" # \ escape the $

echo "A monkey-tailed boy named Goku is found by an old martial \
arts expert who raises him as his grandson. One day Goku meets a \
girl named Bulma and together they go on a quest to retrieve the seven D\
ragon Balls"
